/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.pos.gui.dialog;

import com.aldrin.pos.data.dao.impl.UserAccountDAOImpl;
import com.aldrin.pos.model.UserAccount;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogChangePassword extends javax.swing.JDialog {

    private UserAccount userAccount;
    private static boolean currentPassword = false;
    private static boolean reTypePassword = false;
    private com.aldrin.pos.gui.JFrameAldrinPOS jFrameAldrinPOS;

    /**
     * Creates new form JDialogChangePassword
     */
    public JDialogChangePassword(com.aldrin.pos.gui.JFrameAldrinPOS parent, boolean modal, UserAccount userAccount) {
        super(parent, modal);
        initComponents();
        this.jFrameAldrinPOS = parent;
        jButtonChangePassword.setEnabled(false);
        this.userAccount = userAccount;
        jTextFieldUsername.setText(userAccount.getUsername());
        jPasswordFieldCurrentPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Current password");
        jPasswordFieldNewPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "New password");
        jPasswordFieldReTypeNewPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Re-type new password");
//        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(70, 130, 180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldReTypeNewPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldCurrentPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jLabelErrorMessage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonChangePassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("USERNAME");
        jLabel1.setMaximumSize(new java.awt.Dimension(61, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(61, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(61, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));

        jTextFieldUsername.setEditable(false);
        jTextFieldUsername.setFocusable(false);
        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(7, 30));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 55, 330, -1));

        jPasswordFieldReTypeNewPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        jPasswordFieldReTypeNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldReTypeNewPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordFieldReTypeNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 200, 330, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CURRENT PASSWORD");
        jLabel3.setMaximumSize(new java.awt.Dimension(138, 22));
        jLabel3.setMinimumSize(new java.awt.Dimension(138, 22));
        jLabel3.setPreferredSize(new java.awt.Dimension(138, 22));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 140, -1));

        jPasswordFieldCurrentPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldCurrentPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordFieldCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 102, 330, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 30));

        jPasswordFieldNewPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        jPasswordFieldNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldNewPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordFieldNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 150, 330, -1));

        jLabelErrorMessage.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabelErrorMessage.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 470, 30));

        jLabel5.setText("RE-TYPE NEW PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 30));

        jButtonChangePassword.setIcon(new FlatSVGIcon("svg/save.svg",24,24));
        jButtonChangePassword.setText("Save");
        jButtonChangePassword.setPreferredSize(new java.awt.Dimension(400, 32));
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChangePassword);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 470, 60));

        setSize(new java.awt.Dimension(508, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldCurrentPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldCurrentPasswordKeyReleased
        if (jPasswordFieldCurrentPassword.getText().equals(userAccount.getPassword().toString())) {
            jPasswordFieldCurrentPassword.putClientProperty("JComponent.outline", "success");
            setCurrentPassword(true);
            validateFields();
            jLabelErrorMessage.setText("");
        } else {
            setCurrentPassword(false);
            validateFields();
            jLabelErrorMessage.setText("Current password did not match.");
            jPasswordFieldCurrentPassword.putClientProperty("JComponent.outline", "error");
        }

    }//GEN-LAST:event_jPasswordFieldCurrentPasswordKeyReleased

    private void jPasswordFieldNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldNewPasswordKeyReleased
        if (!jPasswordFieldNewPassword.getText().toString().equals(jPasswordFieldCurrentPassword.getText().toString())) {
            jPasswordFieldReTypeNewPassword.putClientProperty("JComponent.outline", "success");
            setReTypePassword(true);
            validateFields();
            jLabelErrorMessage.setText("");
        } else {
            setReTypePassword(false);
            validateFields();
            jPasswordFieldNewPassword.putClientProperty("JComponent.outline", "error");
            jLabelErrorMessage.setText("Current password is not allowed.");

        }
    }//GEN-LAST:event_jPasswordFieldNewPasswordKeyReleased

    private void jPasswordFieldReTypeNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldReTypeNewPasswordKeyReleased
        if (jPasswordFieldNewPassword.getText().toString().equals(jPasswordFieldReTypeNewPassword.getText().toString())) {
            jPasswordFieldReTypeNewPassword.putClientProperty("JComponent.outline", "success");
            setReTypePassword(true);
            validateFields();
            jLabelErrorMessage.setText("");
        } else {
            setReTypePassword(false);
            validateFields();
            jPasswordFieldReTypeNewPassword.putClientProperty("JComponent.outline", "error");
            jLabelErrorMessage.setText("Error input please try again.");

        }
    }//GEN-LAST:event_jPasswordFieldReTypeNewPasswordKeyReleased

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        UserAccountDAOImpl userAccountDAOImpl = new UserAccountDAOImpl();
        userAccount.setPassword(jPasswordFieldReTypeNewPassword.getText());
        int response = JOptionPane.showConfirmDialog(jFrameAldrinPOS, "Are you sure to change your password?", "Change password confirmation", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            if (userAccountDAOImpl.changePassword(userAccount) == true) {
                JOptionPane.showMessageDialog(jFrameAldrinPOS, "Password is successfully change.", "Message", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            }
        }

    }//GEN-LAST:event_jButtonChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldCurrentPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldReTypeNewPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
private void validateFields() {
        if (isCurrentPassword() == true && isReTypePassword() == true) {
            jButtonChangePassword.setEnabled(true);
        } else {
            jButtonChangePassword.setEnabled(false);
        }
    }

    /**
     * @return the currentPassword
     */
    public static boolean isCurrentPassword() {
        return currentPassword;
    }

    /**
     * @param aCurrentPassword the currentPassword to set
     */
    public static void setCurrentPassword(boolean aCurrentPassword) {
        currentPassword = aCurrentPassword;
    }

    /**
     * @return the reTypePassword
     */
    public static boolean isReTypePassword() {
        return reTypePassword;
    }

    /**
     * @param aReTypePassword the reTypePassword to set
     */
    public static void setReTypePassword(boolean aReTypePassword) {
        reTypePassword = aReTypePassword;
    }

}
